version: '3.5'

services:
  etcd:
    image: docker.1ms.run/milvusdb/etcd:v3.5.18-r1
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:2379
      - ETCD_LISTEN_PEER_URLS=http://127.0.0.1:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://127.0.0.1:2380
      - ETCD_INITIAL_CLUSTER=default=http://127.0.0.1:2380
      - ETCD_DATA_DIR=/etcd
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 10s
      retries: 5

  pulsar:
    image: milvusdb/pulsar:v2.8.2-m1
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/pulsar:/pulsar/data
    environment:
      - nettyMaxFrameSizeBytes=104867840
      - defaultRetentionTimeInMinutes=10080
      - defaultRetentionSizeInMB=8192
      - PULSAR_PREFIX_maxMessageSize=104857600
      - PULSAR_MEM=-Xms512m -Xmx1g
      - PULSAR_GC=-XX:+UseG1GC
    ports:
      - "6650:6650"
      - "18080:8080"
    depends_on:
      - etcd
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/admin/v2/clusters"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: docker.1ms.run/minio/minio:RELEASE.2024-05-28T17-19-04Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/azurite:/data
    command: azurite-blob --blobHost 0.0.0.0
    ports:
      - "10000:10000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  jaeger:
    image: docker.1ms.run/jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:16686/"]
      interval: 30s
      timeout: 10s
      retries: 3

  gcpnative:
    image: docker.1ms.run/fsouza/fake-gcs-server:latest
    command: -scheme http -public-host storage.gcs.127.0.0.1.nip.io:4443
    ports:
      - "4443:4443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4443/storage/v1/b"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: milvus_dev 